### ISSUE TITLE
Does this still use java swing?

### ISSUE THREAD

**Issue by lvxingtu** [reportmill/SnapCode#1]
Hello, I successfully ran the source. Does this still use java swing?

**Comment by lvxingtu** [comment]
It's a amazing project. And I want to spend a long time enjoying the code.

**Comment by reportmill** [comment]
Thanks for the kind words! Yes, SnapCode is still Swing under the hood, though it's really built on top of SnapKit, which is a portable Java UI kit that runs on top of Swing, JavaFX or HTML DOM (check out the demos: https://www.reportmill.com/snaptea/). (Although it would be a challenge to run SnapCode in the browser :-)).

**Comment by lvxingtu** [comment]
@reportmill  Hello. The UI kit runs on top of Swing, so which a swing component support rich code area, I  view source code a few hours, and can't figure out that.

**Comment by reportmill** [comment]
SnapKit tries to be a full UI kit with a few abstractions. The main two are: mapping input events to SnapKit and mapping SnapKit painting to a native platform device. For Swing, this is done in snap.swing.SWRootView. In there you can see that when a window is created in SnapKit, it creates a Swing window with a SWRootView as root pane. SWRootView then maps the input events and Graphics2D for SnapKit.
