### ISSUE TITLE
most menu bar items not working

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#14]
Some not working:
- New File
- Open File
- Save
- Save As
- Revert to saved
- Undo
- Redo
- Cut
- Copy
- Paste
- Select All
- Support Page
- Tutorial

Also kindly look into adding "Duplicate line" and "Delete line" menu items.

**Comment by mmkathurima** [comment]
How can I make a pull request. I can fix some of these

**Comment by reportmill** [comment]
I'm ashamed to admit that I don't know - I've never worked in a team environment with GitHub.

Maybe just hitting the "New Pull Request" under the pull request tab. I'm not sure if you have to fork or something. I don't know anything about the "collaborators" section, but I just added you.

**Comment by mmkathurima** [comment]
Faced this: `org.gradle.api.UnknownProjectException: Project with path ':SnapKit' could not be found in root project 'SnapCode'`

**Comment by reportmill** [comment]
Right - SnapCode has a few dependencies: SnapKit, SnapCharts, SnapBuilder (fortunately, those projects don't have any dependencies, so it ends there). There is a SnapKitGL dependency, but you comment that out.

If you git clone all 4 projects into the same dev directory, gradle or IntelliJ will find them all. Though you will probably have to add a settings.gradle file to that directory. I call my dev directory "SnapDev", so my settings.gradle file looks like this:

rootProject.name = 'SnapDev'

include 'SnapKit'
include 'SnapBuilder'
include 'SnapCharts'
include 'SnapCode'

My phone number is on the contact page at reportmill.com. Feel free to text me so we can do chat so you can quickly get questions answered. Or email jeff at reportmill (slower :-)).

I can modify the project to be more friendly (e.g., those dependencies could be changed to fall back on maven). Hasn't been a reason to until now. :-)

**Comment by mmkathurima** [comment]
do you have skype? I'm not American so texting you may be an issue

**Comment by reportmill** [comment]
Yep: I'm "reportjeff". Running it now (though sometimes I forget).

**Comment by mmkathurima** [comment]
All are working now except Open File (this may require a dialog that @reportmill could help with), Save As (this may also require a dialog), Revert to Saved (not sure what this is about). Note that your (@reportmill) input is needed on the duplicate line menu item as it affects undo and redo.

**Comment by mmkathurima** [comment]
None of the Edit menu items are working

**Comment by reportmill** [comment]
The Edit menu items are all working now. I had to add a "SharedAction" facility to SnapCode, so that the menu items could do different things depending on what view is focused when menu is selected (TextArea, TextField, etc.).

Sorry that took so long. :-)
