### ISSUE TITLE
most shortcuts not working

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#15]
Examples are
- <kbd>Ctrl + N</kbd> - New file
- <kbd>Ctrl + O</kbd> - Open file
- <kbd>Ctrl + W</kbd> - Close file
- <kbd>Ctrl + U</kbd> - Revert to saved
- <kbd>Ctrl + Q</kbd> - Quit

Not sure about <kbd>Ctrl + S</kbd> and <kbd>Ctrl + Shift + S</kbd> (Save and Save as).
Also consider implementing <kbd>Ctrl + D</kbd> to duplicate line and another shortcut to delete line.

**Comment by mmkathurima** [comment]
Fixed all but <kbd>Ctrl + O</kbd> (probably involves dialog which @reportmill could help with), <kbd>Ctrl + U</kbd> (Not sure what this is about), <kbd>Ctrl + Shift + S</kbd> (also involves dialog)

**Comment by reportmill** [comment]
Any thoughts on how we do a pull request?

**Comment by reportmill** [comment]
Ah - never mind, I see they are in there!

**Comment by reportmill** [comment]
Fixed in the latest update today.
