### ISSUE TITLE
Support for user input

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#16]
Kindly provide support for user input eg `new Scanner(System.in).nextLine()`, `new BufferedReader(new InputStreamReader(System.in)).readLine()`, `System.console().readLine()` etc.

**Comment by reportmill** [comment]
I added support for this today - along with a "Program Input" text field:
<img width="1070" alt="SystemInput" src="https://github.com/reportmill/SnapCode/assets/9698378/638f6a98-6580-4ccd-8b36-5dcdb9e5de2c">

**Comment by reportmill** [comment]
I think it could probably be improved. The 'chat' interface is nice - though I think it would be nice if I figured out how to make it act more like terminal input, too.

**Comment by mmkathurima** [comment]
Hello. It's been a while. Wish I could test it but it appears the jar download link on your site is broken.

**Comment by reportmill** [comment]
Whoops - thanks for pointing this out. I moved the jar to a new directory and forgot to update the links on the download page (https://reportmill.com/SnapCode/download.html).
