### ISSUE TITLE
Support for dependencies

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#17]
It would be great if you added maven, gradle and/or own jar support to add dependencies to a jepl.

**Comment by reportmill** [comment]
I do have some support for this for a real project (which SnapCode supports, but it hasn't been tested or used in a while). I will have to port this to the simpler Jepl projects, which should not be much work.

The support is with a JSON build file configured in the app (see pic).

Although I was wondering if I should support a directive so you could add these to the Jepl code. Maybe something like:

maven "com.reportmill:snapkit:2023.07"

![image](https://github.com/reportmill/SnapCode/assets/9698378/e0025865-33f2-4ff9-975c-27d8211223b3)

**Comment by mmkathurima** [comment]
IMO better to support dependency management in a settings window rather than a directive. I reckon users may prefer the dependencies to persist between sessions. Additionally, add a default imports section which would also persist.

**Comment by reportmill** [comment]
I think you're right. The 'default imports' feature has also occurred to me and should be easy to add.

**Comment by mmkathurima** [comment]
Hello Jeff. If I may suggest, kindly give this the highest priority.

**Comment by reportmill** [comment]
Sounds good - I've moved it to the top of the list. It will probably take a few days though. :-)

**Comment by mmkathurima** [comment]
Hello, how's this going? :-)

**Comment by reportmill** [comment]
Sorry for the delay - I got sidetracked by several basic issues (lambda issues, enums, switch statements), and was out of town a few days. I’m hoping to get back on track with this in the next couple days.

**Comment by reportmill** [comment]
I made good progress on this today. I need to clean it up a little, but it should be ready by late tomorrow.

**Comment by reportmill** [comment]
<img width="385" alt="BuildFile" src="https://github.com/reportmill/SnapCode/assets/9698378/04d916a5-b185-47e3-9887-58c0a9b09f5f">
<img width="413" alt="ExternalCode" src="https://github.com/reportmill/SnapCode/assets/9698378/2ffc7499-557a-46b3-b799-8d8eff7b8f84">

**Comment by mmkathurima** [comment]
Looking good. Hope the dependencies can persist even after the application is closed and reopened. Also, what about the default imports feature?

**Comment by reportmill** [comment]
I have this working - for simple cases anyway. I even have it working in the browser.

I don't yet have it downloading the .pom and recursively including a package's dependencies. But give it a try and let me know what you think.

If you have a good use-case/example, let me know what it is. If I find a good one, I'll add it to the build-in samples.

**Comment by mmkathurima** [comment]
> If you have a good use-case/example, let me know what it is. If I find a good one, I'll add it to the build-in samples.

A simple example is using the `org.json` library to serialize a model class and print the serialized string.

**Comment by reportmill** [comment]
A simple sanity check worked for me:

<img width="916" alt="JSON" src="https://github.com/reportmill/SnapCode/assets/9698378/f19311d0-d55c-4382-bf05-3c3391fdfeb4">

I need to look into how to use it to serialize some objects though.

**Comment by mmkathurima** [comment]
Ok. For another scenario try creating a JavaFX Stage containing a label.
