### ISSUE TITLE
Support multiple jdk/java versions

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#18]
LINQPad has a feature whereby you can switch between available .NET versions including preview versions and thus use features available in that version.
 
This would be great if implemented in SnapCode whereby you can even use preview features (as of writing, Java 21 preview features like string interpolation). Switching from Java 11 to 17 enables multiline strings for example, while switching from 11 to 8 prohibits the `var` keyword and `String.isBlank` etc.

This is great if I want to preview features in newer jdks.

**Comment by reportmill** [comment]
I definitely want to add this, but for the next few months, I am limited to Java 8 by the CheerpJ guys. They have committed to adding at least Java 11 in a few months (hopefully higher). I'll reopen this and make it a priority when the higher versions become available.
