### ISSUE TITLE
Can't create new jepl files

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#20]
Provide ways to create a new jepl file.
![image](https://github.com/reportmill/SnapCode/assets/84718271/6628cda2-28b0-4a9d-ab25-586aa8fa97e7)

**Comment by reportmill** [comment]
Good feedback, thanks!

And done!

<img width="450" alt="NewJeplFile" src="https://github.com/reportmill/SnapCode/assets/9698378/8a53c62a-bcda-43e5-9c07-bf75ae672ff0">
