### ISSUE TITLE
operators

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#21]
Look into support for `|`, `&`, `^`,`<<`,`>>`,`~` operators with their respective assignment operators. I may not have tested all operators so this may not be so comprehensive... :-)

**Comment by reportmill** [comment]
This is done:
   - added support for bitwise math ops: BitAnd, BitOr, BitXOr, ShiftLeft, ShiftRight, ShiftRightUnsigned, BitComp
   - Added support for bitwise assignment ops: BitAnd, BitOr, BitXor, ShiftLeft, ShiftRight, ShiftRightUnsigned
