### ISSUE TITLE
try with resources block support

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#22]
The following code raises an invalid assignment compile time error:
```java
import java.nio.file.Files;
import java.nio.file.Path;

try (Stream<Path> walk = Files.walk(Path.of("."))) {
    for (Path path : walk.collect(Collectors.toList())) {
        if (!Files.isDirectory(path))
            System.out.println(path);
        else System.err.println(path);
    }
}
```

```
Error: Invalid assignment type
Error: Can't resolve id: walk
Error: Can't resolve id: walk
Error: Can't resolve method: collect(Collector<Object,Object,List<Object>>)
```
Maybe there is no support for try-with resources blocks?

**Comment by reportmill** [comment]
This is true - I haven't added this yet. It should be just a couple of hours work.

I ended up getting diverted for a few weeks adding support for CheerpJ 3 (with native DOM bindings) then another couple weeks on re-architecting editor text. I'm off for a few days this week, but I plan to get back to fixing all of your bug reports. I really appreciate the time and effort you have made!

I'm also excited about your Expresso Pad and hope to play with it soon. Did you see the other new one that showed up this week: https://dev.java/playground/ ?

It's rudimentary from a code editing standpoint (and written in JavaScript), but it hits the real compiler via client/server. SnapCode also hits the real compiler on the desktop for full projects, but I would like to do this for snippets sometime in the next few months (at least as an option).

**Comment by mmkathurima** [comment]
Too bad their dev.java playground doesn't have autocomplete and such.
Otherwise looking forward to you closing as many issues as possible.
Also looking forward to feedback and pull requests for Espresso Pad.

**Comment by mmkathurima** [comment]
How do you build your jars? Mine tells me that the App class was not found.

**Comment by reportmill** [comment]
Sorry for the delay (I was out all last week). Can you post the full error? I assume you are using ./gradlew build?

In the SnapCode build.gradle you can comment out the SnapKitGL, that might help slightly.

**Comment by mmkathurima** [comment]
Sorry for the delay.
The errors I had posted in the first post were all that were thrown. Nothing else.

**Comment by reportmill** [comment]
This is now fixed. Although I had to use Paths.get() instead of Path.of(), because Path.of() isn't available until Java 11.

**Comment by reportmill** [comment]
<img width="1217" alt="TryWithResources" src="https://github.com/reportmill/SnapCode/assets/9698378/ad65ad4f-18ab-4193-a595-7bd28f40d0e2">
