### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#25]
Would like it if you added proper debugging support:
- Breakpoints
- View variable values at breakpoints
- Step over
- Step into
- Step out
- Evaluate expressions
And other debugging related features I may have not thought of.

**Comment by reportmill** [comment]
These are all supported in the desktop version. There are some missing features in the web version that prevent this, but I hope to add as soon as CheerpJ makes this possible. I'm going to close this for now.

**Comment by mmkathurima** [comment]
Kindly update the desktop version on your website to the latest build

**Comment by reportmill** [comment]
Sorry for the delay - it's updated now.
