### ISSUE TITLE
.gfar import with clear cache leads to build errors

### ISSUE THREAD

**Issue by leshlush** [reportmill/SnapCode#27]
At some point, .gfar imports got broken. If a student has already run a Greenfoot project in SnapCode and such a project is in their cache, then everything works fine. However, if a student has a clear cache or is using SnapCode for the first time, then after import, the Greenfoot project will not build.

Build error: package greenfoot does not exist.

**Comment by reportmill** [comment]
Looks like I broke this on Friday by adding a stupid check to the run button to make sure the main class file exists (the run button kicks off a build, so a check for the class file here was wrong).

There is also an underlying issue that has gone unnoticed that the original build doesn't wait for all dependencies to exist - I'm going to fix that today in a separate issue.
