### ISSUE TITLE
Inheritance diagram

### ISSUE THREAD

**Issue by leshlush** [reportmill/SnapCode#30]
Students reported that they missed seeing their classes organized by Actors and Worlds in a class diagram. Found it harder to locate classes they commonly edited or differentiate between types of classes.
![image](https://github.com/reportmill/SnapCode/assets/16392715/02d7ea5d-98f0-4043-b7e0-825f5ce5cea8)

**Comment by reportmill** [comment]
Okay, I've got a first implementation of this with a new "Classes" tab in the right tool tray:

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/ac7bb276-c1cf-40ed-b354-e40f43620dad">

**Comment by reportmill** [comment]
It renders a little more plainly than Greenfoot right now, but on the plus side, it is selectable and shows the code immediately when you click on a class tab (and selection stays in sync when change to other source files).

We might want to consider these enhancements:

- Add mini icons to class labels in tree (this is a little hard since SnapCode
                doesn't really know about Greenfoot conventions)
- Add lines/arrows option to SnapKit TreeView
- Maybe move Classes tab to left side by "Project" since there is overlap in these tools?

**Comment by leshlush** [comment]
> It renders a little more plainly than Greenfoot right now, but on the plus side, it is selectable and shows the code immediately when you click on a class tab (and selection stays in sync when change to other source files).
> 
> We might want to consider these enhancements:
> 
>     * Add mini icons to class labels in tree (this is a little hard since SnapCode
>       doesn't really know about Greenfoot conventions)
> 
>     * Add lines/arrows option to SnapKit TreeView
> 
>     * Maybe move Classes tab to left side by "Project" since there is overlap in these tools?

Hey Jeff, I think this is a great start. Agreed on your enhancement ideas.

1.  The mini icons are a good idea, but probably something that can wait. Definitely more of a "nice to have" than a necessity.
2. Arrows are good because they lead straight into doing a unit on diagramming and UML.
3. Moving classes to the left side I'm not sure on. Probably good to get some student and teacher feedback first.

The related issue 31 on subclassing workflow ( https://github.com/reportmill/SnapCode/issues/31 ) is probably highest priority, but probably hard to do for the same reason as mini-icons.

**Comment by reportmill** [comment]
Sounds good - I'll skip #1 for now and skip #3 all together.

The arrows and lines would be a cool feature for SnapKit TreeView. I'll put that on the short list.
