### ISSUE TITLE
no anonymous classes support

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#4]
The code below will cause execution to halt:
```java
new Object() {
    void run() {
        Stream<Float> f = IntStream.range(1, 11).mapToObj(x -> (float) x);
        for (float f1 : f.toArray(Float[]::new))
            System.out.println(f1);
    }
}.run()
```
It seems there is no support for anonymous classes.

**Comment by reportmill** [comment]
This works for me now (although the method reference 'Float[]::new' isn't working. I'll file a separate bug for that.
