### ISSUE TITLE
no var support

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#7]
The following code raises the following error:
```
Error: Cannot infer type: 'var' on variable without initializer
Error: Can't resolve id: var
```
After replacing `var` with `Map.Entry<String, Object>`  and running, (it has no compile time errors) it shows no output:

```java
static String requestBuilder(Map<String, Object> params) {
    StringBuilder res = new StringBuilder("?");
    for (var kv : params.entrySet()) res.append(String.format("%s=%s&", kv.getKey(), kv.getValue()));
    String s = res.toString();
    return s.substring(0, s.length() - 1);
}

static String getPostDataString(HashMap<String, Object> params) throws UnsupportedEncodingException {
    StringBuilder result = new StringBuilder();
    boolean first = true;
    for (Map.Entry<String, Object> entry : params.entrySet()) {
        if (first)
            first = false;
        else
            result.append("&");

        result.append(URLEncoder.encode(entry.getKey(), "UTF-8"));
        result.append("=");
        result.append(URLEncoder.encode(entry.getValue().toString(), "UTF-8"));
    }

    return result.toString();
}

HashMap p = new HashMap<String, Object>();
p.put("name", 50);
p.put("type", "foo");
show(p);

show(requestBuilder(p));
show(getPostDataString(p));

Object s = 5;
System.out.println(s instanceof Integer); 
```

**Comment by reportmill** [comment]
I fixed the use of "var" as a For-Each parameter (and released it).

This example hits a couple of other problems - working on those now.

**Comment by reportmill** [comment]
Okay, the other two issues were caused by missing import for URLEncoder and UnsupportedEncodingException. I've fixed the error checking to report errors much better, so these are easy to find and fix. There isn't yet an auto "Add import for this undefined class", but you can delete the last letter of each class name and retype it and you'll get the completion (which will add the import).

Thanks for this report - I know there are a lot of broken cases, but it is very motivating to have one from a real world person :-).

**Comment by mmkathurima** [comment]
@reportmill It appears the indent bug has crept its way to the August release too. I want to press tab to autocomplete but still ends up indenting.

**Comment by mmkathurima** [comment]
@reportmill  How come the last line isn't being executed `System.out.println(s instanceof Integer);`?

**Comment by reportmill** [comment]
Ah - looks like I was missing support for the 'instanceof' operator. This was easy to add - it's in there and released.

**Comment by mmkathurima** [comment]
I am enjoying the fact that someone is actually listening to user feedback. Thanks and rooting for you!

**Comment by mmkathurima** [comment]
> @reportmill It appears the indent bug has crept its way to the August release too. I want to press tab to autocomplete but still ends up indenting.

Please @reportmill  look into this

**Comment by reportmill** [comment]
I had really hit the doldrums with this project. I haven't gotten any interest or feedback and it has been affecting my motivation. I really appreciate you taking the time to look at it and posting bugs.

To be fair, I haven't done any promotion, so I haven't expected much feedback. I don't think it will truly be interesting until CJ3 is polished (and I have the more native browser JNI implemented). But then I think it could be a popular tool for education (and more).

So thanks again - I hope you keep posting. Good to have these issues documented here, but you can always contact me at jeff at reportmill, too. Would love to hear about your interests.

**Comment by reportmill** [comment]
And I'll add the 'tab to complete' feature ASAP. :-) 

That hadn't occurred to me because I always use "ENTER" in IntelliJ. But I do use tab for completion in other apps, so it certainly makes sense to add it there (I see IntelliJ supports ENTER and TAB).

**Comment by reportmill** [comment]
Okay - 'tab to complete' is now supported. :-)
